# docker-compose.yaml
services:
  orders-service:
    image: orders-service
    build:
      context: .
      dockerfile: Dockerfile
      target: orders-service
    ports:
      - '50051:50051'
    cpus: 0.125
    mem_limit: 128m
  gateway-service:
    image: gateway-service
    depends_on:
      - orders-service
    environment:
      - ORDER_SERVICE_ADDRESS=orders-service:50051
    build:
      context: .
      dockerfile: Dockerfile
      target: gateway-service
    ports:
      - '8080:8080'
    cpus: 0.125
    mem_limit: 128m
